"""add isPhoto column to photos table

Revision ID: 3ba3969291a1
Revises: 
Create Date: 2023-08-11 17:54:05.036658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ba3969291a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projectphotos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isPhoto', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projectphotos', schema=None) as batch_op:
        batch_op.drop_column('isPhoto')

    # ### end Alembic commands ###
