"""add database column

Revision ID: 76164053a403
Revises: aed613a7c0c3
Create Date: 2023-08-29 20:50:02.477709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76164053a403'
down_revision = 'aed613a7c0c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('database', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('database')

    # ### end Alembic commands ###
