"""add caption to photo model

Revision ID: 84e1f4adb26d
Revises: fd1d45695f45
Create Date: 2023-09-06 16:34:43.935342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84e1f4adb26d'
down_revision = 'fd1d45695f45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projectphotos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caption', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projectphotos', schema=None) as batch_op:
        batch_op.drop_column('caption')

    # ### end Alembic commands ###
