"""empty message

Revision ID: a12ebe57f391
Revises: 
Create Date: 2023-08-08 15:53:43.739244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a12ebe57f391'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projectphotos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(), nullable=False))
        batch_op.drop_constraint('projectphotos_project_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projectphotos', schema=None) as batch_op:
        batch_op.create_unique_constraint('projectphotos_project_id_key', ['project_id'])
        batch_op.drop_column('url')

    # ### end Alembic commands ###
