"""add github links for back and front end columns on the Project model

Revision ID: aed613a7c0c3
Revises: c3314abd67c4
Create Date: 2023-08-29 20:35:06.224063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed613a7c0c3'
down_revision = 'c3314abd67c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_fe', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('github_be', sa.String(), nullable=True))
        batch_op.drop_column('github')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('github_be')
        batch_op.drop_column('github_fe')

    # ### end Alembic commands ###
