"""add tech columns to project model

Revision ID: c3314abd67c4
Revises: 3ba3969291a1
Create Date: 2023-08-20 08:12:40.047876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3314abd67c4'
down_revision = '3ba3969291a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('back_end', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('front_end', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('css', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('css')
        batch_op.drop_column('front_end')
        batch_op.drop_column('back_end')

    # ### end Alembic commands ###
